name: leaf2mqtt
version: 0.1.1
publish_to: 'none'
dependencies:
  dartnissanconnectna:
    git: https://gitlab.com/tobiaswkjeldsen/dartnissanconnectna
  dartnissanconnect:
    git:
      url: https://github.com/kamiKAC/dartnissanconnect
      ref: v1.0.5
  dartcarwings:
    git:
      url: https://github.com/Tobiaswk/dartcarwings
      ref: master
  mqtt_client: ^9.6.1
  logging: ^1.0.1
environment:
  sdk: '>=2.12.0 <4.0.0'
